config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  delete 'pages/:id/delete'  => 'pages#destroy', as: :delete
  resources :admins, only: [:index] do
    collection do
      get 'not_sponsorschip'
      get 'listing_sponsorship'
      get 'listing_more_sponsorship'
      get 'search_sponsorship_init'
      post 'listings_result'
      post 'more_sponsorship_result'
      post 'search_sponsorship_result'
    end
  end
  resources :sponsorships, only: [:index] do
    collection do
      post 'friend'
      get 'add_godchild'
    end
  end
  devise_for :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def fullname
    "#{lastname.capitalize} #{firstname.capitalize}"
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def index
  end

  def not_sponsorschip
    @not_sponsorship = SponsorshipService.new(User).not_sponsorship
  end

  def listing_sponsorship
  end

  def listing_more_sponsorship
  end

  def search_sponsorship_init
    @godchilds = User.select(:email, :sponsorship_id).where.not(sponsorship_id: nil)
  end

  def search_sponsorship_result
    sponsorship_service = SponsorshipService.new(User, params[:godchilds])
    @user = sponsorship_service.search_sponsorship
    @godchilds = sponsorship_service.all_godchilds_for_sponsorship
  end

  def more_sponsorship_result
    if params[:number].present?
      @result_more_sponsorship = SponsorshipService.new(User,params[:number]).users_more_sponsorship
    else
      @error = " Vous n'avez pas ajouté un chiffire"
    end
  end

  def listings_result
    if params[:number].present?
      @result_listing = SponsorshipService.new(User).listing_sponsorship(params[:number])
    else
      @error = " Vous n'avez pas ajouté un chiffire"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:firstname, :lastname, :sponsorship_id, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) {|u| u.permit(registration_params << :current_password)}
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up){ |u| u.permit(registration_params) }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def destroy
    SponsorshipService.new(User, params[:id]).reorganization_sponsorship
    redirect_to root_path, alert: 'Votre compte a bien été supprimé'
  end
end

app/controllers/sponsorships_controller.rb
class SponsorshipsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  before_action :set_user, only: [:friend]

  def index
  end

  def add_godchild
    # create filleul
    return redirect_to root_path, alert: " Vous êtes déja inscrit" if User.find_by(email: params[:email_sponsorship])

    if params[:email_sponsorship]
      pwd = Digest::MD5.hexdigest(params[:email_sponsorship])
      user = User.new(email: params[:email_sponsorship], password: pwd, password_confirmation: pwd, sponsorship_id: params[:sponsorships_id])
      if user.save
        SponsorshipMailer.send_password(user, pwd).deliver_now
        redirect_to root_path(params[:sponsorship]), notice: "Vous allez recevoir un email avec votre mots de passe provisoire." and return
      end
    else
      redirect_to root_path, alert: "Une erreur est survenue veuillez contacter le site." and return
    end
  end

  def friend
    SponsorshipMailer.invite_sponsorship(params[:email], @user).deliver_now
    redirect_to  sponsorships_path, notice: 'Votre email à bien été envoyé.'
  end

  private

  def set_user
    @user = User.find_by(id: params[:user])
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sponsorships_helper.rb
module SponsorshipsHelper
end

app/views/admins/listing_more_sponsorship.html.haml
.container
  %p Trouver tous les utilisateurs qui ont parrainé plus de x utilisateurs
  = form_tag more_sponsorship_result_admins_path, remote: true do
    = text_field_tag :number, '', placeholder: "Ajouter le nombre"
    = submit_tag "Trouver"
  .results

app/views/admins/listing_sponsorship.html.haml
.container
  %p Lister les X utilisateurs ayant parrainé le plus grand nombre de personnes
  = form_tag listings_result_admins_path, remote: true do
    = text_field_tag :number, '', placeholder: "Ajouter le nombre"
    = submit_tag "Listings"


  .results

app/views/admins/listings/_listings.html.haml
%p.ui.info.message= "Vous avez trouvé  #{@result_listing.count} utilisateur(s) qui ont parrainés le plus de monde"

%table.ui.single.line.table
  %thead
    %tr
      %th Fullname or Email
      %th sponsorship total
  %tbody
    - @result_listing.each do |l|
      %tr
        %td
          = l[:user]
        %td
          = l[:count]

app/views/admins/listings/_more_sponsorship.html.haml
%p.ui.info.message
  = "Vous avez trouvé  #{@result_more_sponsorship.count} utilisateur(s) qui ont parrainés le plus de monde"
%table.ui.single.line.table
  %thead
    %tr
      %th Fullname
      %th sponsorship total
  %tbody
    - @result_more_sponsorship.each do |l|
      %tr
        %td
          = l[:user]
        %td
          = l[:count]

app/views/admins/listings/_search_sponsorship.html.haml
.container
  %table.ui.single.line.table
    %thead
      %tr
        %th Parrain
        %th Filleul(s)
    %tbody
      %tr
        %td
          - if @user.firstname && @user.lastname
            = @user.fullname
          - else
            = @user.email
        %td
          - @godchilds.each do |g|
            - if g.firstname && g.lastname
              = g.fullname
            - else
              = g.email+ " "

app/views/admins/listings_result.js.haml
- if params[:number].present?
  $('.results').html("#{j render 'admins/listings/listings' }")
- else
  $('.results').html("#{j "Vous n'avez pas ajouté un chiffre pour votre recherche"}")

app/views/admins/more_sponsorship_result.js.haml
- if params[:number].present?
  $('.results').html("#{j render 'admins/listings/more_sponsorship' }")
- else
  $('.results').html("Vous n'avez pas ajouté de chiffre")

app/views/admins/not_sponsorschip.html.haml
.container
  - if @not_sponsorship
    %table.ui.single.line.table
      %thead
        %tr
          %th Les utilisateurs n'ayant parrainé personne
      %tbody
        - @not_sponsorship.each do |ns|
          %tr
            %td
              - if ns.firstname && ns.lastname
                = ns.fullname
              - else
                = ns.email
  - else
    %p Aucune réponse

app/views/admins/not_spoonsorschip.html.haml
.container
  - if @not_sponsorship
    %table.ui.single.line.table
      %thead
        %tr
          %th Les utilisateurs n'ayant parrainé personne
      %tbody
        - @not_sponsorship.each do |ns|
          %tr
            %td
              - if ns.firstname && ns.lastname
                = ns.fullname
              - else
                = ns.email
  - else
    %p Aucune réponse

app/views/admins/search_sponsorship_init.html.haml
.container
  - if @godchilds.any?
    = form_tag search_sponsorship_result_admins_path, remote: true do
      = select_tag("godchilds", options_from_collection_for_select(@godchilds, "sponsorship_id", "email"))
      = submit_tag "Trouver"
    .results
  - else
    %p.ui.error.message
      Ils n y a pas de filleul(s) en ce moment

app/views/admins/search_sponsorship_result.js.haml
$('.results').html("#{j render 'admins/listings/search_sponsorship' }")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Socialddict</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel='stylesheet' href="http://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.2/semantic.min.css" />
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>

    <% if request.path_info == '/admins' || request.path_info == '/admins/listing_sponsorship' || request.path_info == '/admins/listing_more_sponsorship' || request.path_info == '/admins/search_sponsorship_init' || request.path_info == "/admins/not_sponsorschip" %>
      <%= render 'layouts/header/header_admin' %>
    <% else %>
      <%= render 'layouts/header/header_user' %>
    <%end %>
    <div class="ui container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/header/_header_admin.html.haml
.ui.menu
  .header.item SocialDdict
  = link_to "Personnes qui n'ont pas de parrain", not_sponsorschip_admins_path, class: "item"
  = link_to "Lister les X utilisateurs ayant parrainé", listing_sponsorship_admins_path, class: "item"
  = link_to "Trouver tous les users qui ont parrainé plus de x sponsorship", listing_more_sponsorship_admins_path, class: "item"
  = link_to "Trouver le parrain initial à l’origine de l’inscription d’un utilisateur", search_sponsorship_init_admins_path, class: "item"
- if notice
  %p.ui.info.message= notice
- if alert
  %p.ui.error.message= alert

app/views/layouts/header/_header_user.html.haml
.ui.menu
  .header.item SocialDdict
  - if user_signed_in?
    = link_to 'Editer le profil', edit_user_registration_path, class: "item"
    = link_to 'Parrainer un ami',   sponsorships_path, class: "item"
    = link_to 'Supprimer', delete_path(current_user), method: :delete, class: "item"
    = link_to 'Déconection', destroy_user_session_path, method: :delete, class: "right item"

  - else
    = link_to 'Connexion', new_user_session_path, class: "right item"
- if notice
  %p.ui.info.message= notice
- if alert
  %p.ui.error.message= alert

app/views/pages/index.html.haml
%h1 Pages#index
%p Find me in app/views/pages/index.html.haml

app/views/sponsorships/index.html.haml
.ui.middle.aligned.center.aligned.grid
  .column
    %h1.ui.teal.image.header
      .content
        Parrainer un ami

    = form_tag friend_sponsorships_path(user: current_user), class: 'ui large form' do
      .ui.stacked.segment
        .field
          .ui.left.icon.input
            %i.at.icon
            = text_field_tag :email, '', placeholder: "Email du filleul"
      = submit_tag "Parrainer", class: "ui button"